version: "3.0"
services:
  jupyter:
    build:
      context: docker/jupyter/.
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - .:/usr/app
  postgres:
    build: docker/postgres/.
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  rq_worker:
    build: docker/jupyter/.
    depends_on:
      - redis
    volumes:
      - .:/usr/app
    entrypoint:
      - "tini"
      - "--"
      - "rqworker"
      - "-u"
      - "redis://redis:6379"
    deploy:
      mode: replicated
      replicas: 3
  rq_monitor:
    depends_on:
      - redis
    build: docker/jupyter/.
    ports:
      - "5000:5000"
    entrypoint:
      - "tini"
      - "--"
      - "rq-dashboard"
      - "-H"
      - "redis"
      - "-p"
      - "5000"
volumes:
  pg_data:
  redis_data:
