version: "2.0"
services:
  jupyter:
    build: docker/jupyter/.
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/app
  postgres:
    build: docker/postgres/.
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
